#!/usr/bin/ruby

require_relative 'sheet'

sheet = Io::Creat::Slipstick::Layout::Sheet.new( 297, 200, 10, 5, 15 )

  sheet.create_label( "LOGAREX 27403-II: L P K A | B CI C | D S T ST" )
  # LOGAREX 27403-II
  strip = sheet.create_strip( 22.0, 260.0, 7.0, 13.0, 7.0 )
    #scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LIN_DECIMAL, "", 0 )
    #  scale.set_params( 25 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LIN_DECIMAL, "log x", 0.33 )
      scale.set_params( 10 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::TGN_PYTHAG, "√(1-x²)", 0.33 )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "x³", 0.33 )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 3 )
      scale.set_flags( 0 )
      scale.add_constants( )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "x²", 0.5, true )
      scale.set_params( 2 )
      scale.add_constants( )
      #scale.set_overflow( 2.0 )

  strip = sheet.create_strip( 18.0, 260.0, 7.0, 13.0, 7.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "x²", 0.5 )
      scale.set_params( 2 )
      #scale.set_overflow( 2.0 )
      scale.add_constants( )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "1/x", 0.33, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 1, true )
      scale.add_constants( )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "x", 0.5, true )
      scale.set_params( 1 )
      #scale.set_overflow( 2.0 )
      scale.add_constants( )

  strip = sheet.create_strip( 18.0, 260.0, 7.0, 13.0, 7.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_POWER, "eˣ", 0.5 )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 1 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_POWER, "e ⁰·ˣ", 0.33, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 10 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_POWER, "e ⁰·⁰ˣ", 0.5, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 100 )

  strip = sheet.create_strip( 22.0, 260.0, 7.0, 13.0, 7.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LOG_DECIMAL, "x", 0.5 )
      scale.set_params( 1 )
      scale.add_constants( )
      #scale.set_overflow( 2.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::TGN_SIN, "sin", 0.33, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 90, 5, [ 1, 5, 10, 20 ] )
      scale.set_flags( 0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::TGN_TAN, "tan", 0.33, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 45, 5, [ 1, 5, 10, 20 ] )
      scale.set_flags( 0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::TGN_SINTAN, "s-t", 0.33, true )
      scale.set_style( Io::Creat::Slipstick::Style::SMALL )
      scale.set_params( 6, 0.5, [ 1.0 / 12.0, 0.5 ], 8 )
      scale.set_flags( 0 )

  sheet.create_label( "CM" )
  # standard rule scale in centimeters
  strip = sheet.create_strip( 10, 260.0, 7.0, 13.0, 7.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LIN_DECIMAL, "cm", 0.33 )
      scale.set_params( 26 )
  strip = sheet.create_strip( 10, 260.0, 7.0, 13.0, 7.0 )
    scale = strip.create_scale( Io::Creat::Slipstick::ScaleType::LIN_INCH, "in", 0.33, true )
      scale.set_params( 10 )

puts sheet.render( )

